### ISSUE TITLE
PR commits are cherry-picked instead of the squashed commit

### ISSUE THREAD

**Issue by Lawls91** [korthout/backport-action#342]
Hey just testing this for our repo and I am seeing that squashed PRs cherrypick using the commits on the PR branch, not the final squash commit. I saw this ticket but it has been closed

https://github.com/korthout/backport-action/issues/46

I've not really dug into it yet but is it possible on a squash commit to grab that commit and cherrypick using that?

**Comment by Lawls91** [comment]
I must admit its been a week so I cant fully remember, but I feel like I was having issues with the backport picking up merge commits where main/master had been merged into the PR, but they shouldn't be part of the backport

I'll try and revisit this this week if I can and take another look

**Comment by korthout** [comment]
Thanks @Lawls91! That's a great point!

There's another feature request that will help resolve that problem, which I plan to implement once I've completed #340:
- #341 

Still, even with #341 implemented, there would be cases left where cherry-picking the resulting commit(s) (i.e. the squashed commit or the rebased commits) are preferable. So, eventually I hope to support this as well.

**Comment by jrhemstad** [comment]
I just ran into this as I started using this action. The problem if you squash PRs into `main` and then backport only the cherry-picked commits to another branch is that the commits will no longer be the same, i.e., the release branch will have different commits from the same changes.

I don't see a great way around this problem though because if you just simply backported the squashed commit, then you run the risk of picking up merge commits from `main` and end up merging changes you didn't intend to into your release branch...

**Comment by korthout** [comment]
@jrhemstad Yes, the action only cherry-picks the commits that exist on the merged pull request, at this time.

>you run the risk of picking up merge commits from main and end up merging changes you didn't intend to into your release branch

This would not be a risk if this action would support cherry-picking the squashed commit instead of the commits that exist on the merged pull request. However, it does not support this yet.

It seems you have a specific need for cherry-picking only the squashed commit. Can you elaborate on why you need this specifically? It may help me prioritize this over other issues.

**Comment by jrhemstad** [comment]
> Can you elaborate on why you need this specifically?

For example, we recently had a PR where the backport action failed when trying to cherry-pick the individual commits: https://github.com/NVIDIA/cccl/pull/574#issuecomment-1793117712

(fyi, the instructions it prints for manually cherry-picking [don't include the logic for skipping merge commits](https://github.com/korthout/backport-action/issues/395))

Trying to manually cherry-pick all of the PR commits was a bit of a pain. In contrast, when we just manually cherry-picked the squashed commit, it applied cleanly without any conflicts or issues: https://github.com/NVIDIA/cccl/pull/663. It would be nice if the action had a way to automate this for us as we never care about preserving the individual commits in the PR we're backporting.

**Comment by korthout** [comment]
Ah yes, reduced chance of conflicts is definitely a benefit of cherry-picking a squashed commit. I see this feature (cherry-picking the resulting commits rather than the pull request's commits) as useful, but there are a few issues I'll prioritize over this at this time, like:
- #395 
- #305 
- #386 
- #384

**Comment by korthout** [comment]
@jrhemstad @Lawls91 [`v2.2.0`](https://github.com/korthout/backport-action/releases/tag/v2.2.0) is out and adds experimental support to [`detect_merge_method`](https://github.com/korthout/backport-action#detect_merge_method). I believe it resolves this issue for you. Please give it a try and let me know what you think.
